// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIGxqvozfuX3zbpwpdYeqymcdhbh_fbjs',
    appId: '1:46087624559:web:85b207c92660ae798cfa9a',
    messagingSenderId: '46087624559',
    projectId: 'bikerzone-d04c3',
    authDomain: 'bikerzone-d04c3.firebaseapp.com',
    storageBucket: 'bikerzone-d04c3.appspot.com',
    measurementId: 'G-YW3GM9Z4FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwMGrLfcTPSRL6GpzVr53whzgIaJ8I-9M',
    appId: '1:46087624559:android:1de00342dbaab89e8cfa9a',
    messagingSenderId: '46087624559',
    projectId: 'bikerzone-d04c3',
    storageBucket: 'bikerzone-d04c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk81U0sMrH41-G6KYZNEY0x97qjBbyo38',
    appId: '1:46087624559:ios:faa3d5fda9eb1d748cfa9a',
    messagingSenderId: '46087624559',
    projectId: 'bikerzone-d04c3',
    storageBucket: 'bikerzone-d04c3.appspot.com',
    iosClientId: '46087624559-3fmikqtv6h9vbu2g2u5airhkac07pkpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikerzone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk81U0sMrH41-G6KYZNEY0x97qjBbyo38',
    appId: '1:46087624559:ios:faa3d5fda9eb1d748cfa9a',
    messagingSenderId: '46087624559',
    projectId: 'bikerzone-d04c3',
    storageBucket: 'bikerzone-d04c3.appspot.com',
    iosClientId: '46087624559-3fmikqtv6h9vbu2g2u5airhkac07pkpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikerzone',
  );
}
